const userNameKeyword = [
  "bookmarks",
  "init",
  "newPage",
  "newQuestion",
  "articles",
  "questions",
  "problems",
  "search",
  "settings",
  "api",
  "termsOfService",
  "privacyPolicy",
  "messages",
  "reports",
  "inquiry",
  "proposal",
  "null",
  "undefined",
];
export default userNameKeyword;