const userNameKeyword = [
  "achievement",
  "api",
  "articles",
  "bookmarks",
  "dev",
  "howToUse",
  "init",
  "inquiry",
  "notifications",
  "privacyPolicy",
  "problems",
  "proposal",
  "questions",
  "reports",
  "search",
  "settings",
  "tags",
  "termsOfService",
  "null",
  "undefined",
];
export default userNameKeyword;