[package]
name = "markdown"
version = "0.1.0"
authors = ["ruku"]
description = "A markdown parser for TellPro"
repository = "https://github.com/sugoruru/TellPro"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
